#!/bin/bash
# Submission script for Nic5
#SBATCH --time=20-01:00:00 # days-hh:mm:ss
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --mem-per-cpu=7500 # megabytes
#SBATCH --partition=bio

export OMP_NUM_THREADS=20
export MKL_NUM_THREADS=20

module --ignore-cache load Nextflow/21.08.0
nextflow run Braker.nf --genome=<genome.fna> --prot=<BrakerDB> --SRA=none --brakermode=<mode> --cpu=20 --currentpath=<PWD>
