#!/bin/bash
# Submission script for Nic5
#SBATCH --time=5-01:00:00 # days-hh:mm:ss
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --mem-per-cpu=25000 # megabytes
#SBATCH --partition=bio

export OMP_NUM_THREADS=20
export MKL_NUM_THREADS=20

module --ignore-cache load Nextflow/21.08.0
nextflow run GENcontams.nf --genomes=GENERA-input --mode=<FIELD1> --ext=<FIELD2> --cpu=20 --dbdir=/data/GENERA/CONTAMS --taxdump=/data/GENERA/CONTAMS/taxdump/ --taxlevel=species
