#!/bin/bash
# Submission script for Nic5
#SBATCH --time=5-01:00:00 # days-hh:mm:ss
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=30
#SBATCH --mem-per-cpu=2625 # megabytes
#SBATCH --partition=bio

export OMP_NUM_THREADS=20
export MKL_NUM_THREADS=20

module --ignore-cache load Nextflow/21.08.0
nextflow run ORPER.nf --reftaxolevel=<FIELD1> --refgroup=<FIELD2> --refgenbank=yes --outgroup=<FIELD3> --outtaxolevel=<FIELD4> --outgenbank=yes --cpu=20 --SSU=<FASTA file> --cdhit=no --drep=no
