Firmicutes
Acidobacteria
Aquificae
Asgard group
Caldiserica/Cryosericota group
Calditrichaeota
Candidatus Hydrothermarchaeota
Chrysiogenetes
Coprothermobacterota
Deferribacteres
Dictyoglomi
DPANN group
Elusimicrobia
Euryarchaeota
FCB group
Fusobacteria
Nitrospinae/Tectomicrobia group
Nitrospirae
Opisthokonta
Proteobacteria
PVC group
Siphoviridae
Spirochaetes
Stramenopiles
Synergistetes
TACK group
Terrabacteria group
Thermodesulfobacteria
Thermotogae
Alveolata
Amoebozoa
Apusozoa
Breviatea
CRuMs
Cryptophyceae
Euglenozoa
Fornicata
Glaucocystophyceae
Haptista
Hemimastigophora
Heterolobosea
Jakobida
Katablepharidophyta
Malawimonadidae
Opisthokonta
Oxymonadida
Parabasalia
Palpitomonas
Rhizaria
Rhodelphea
Rhodophyta
Stramenopiles
Viridiplantae
